### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mkamensky** [leighmcculloch/filecache-ruby#6]
It would be helpful to have a new release, since several deprecated methods that were fixed in `master` no longer exist in ruby 3.2.0

**Comment by leighmcculloch** [comment]
Thanks for bringing this to my attention. Which functions are no longer available? Could you share the build log?

If you're up for opening a PR you're welcome to.

**Comment by mkamensky** [comment]
> Thanks for bringing this to my attention. Which functions are no longer available? Could you share the build log?
> 
> If you're up for opening a PR you're welcome to.

It is already fixed in master, just not released. For example, `File.exists` in place of `File.exist`. Thanks!

**Comment by leighmcculloch** [comment]
Ah yes. Sorry about that. I can cut a new version and publish it.

**Comment by leighmcculloch** [comment]
I've published v1.0.3. Tests pass with Ruby v3.2.0 on my system, so I think it's good. Let me know if you experience any issues!
